/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Rashi = IDL.Record({
  'element' : IDL.Text,
  'description' : IDL.Text,
  'rulingPlanet' : IDL.Text,
  'englishName' : IDL.Text,
  'hindiName' : IDL.Text,
  'dateRange' : IDL.Text,
});
export const Astrologer = IDL.Record({
  'name' : IDL.Text,
  'languages' : IDL.Text,
  'experience' : IDL.Nat,
  'specialization' : IDL.Text,
  'rating' : IDL.Float64,
});
export const Numerology = IDL.Record({
  'title' : IDL.Text,
  'strengths' : IDL.Text,
  'description' : IDL.Text,
  'number' : IDL.Nat,
  'challenges' : IDL.Text,
});
export const VastuTip = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'benefit' : IDL.Text,
});
export const Time = IDL.Int;
export const Horoscope = IDL.Record({
  'date' : Time,
  'message' : IDL.Text,
  'rashi' : IDL.Text,
});
export const KundaliRequest = IDL.Record({
  'id' : IDL.Nat,
  'placeOfBirth' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timeOfBirth' : IDL.Text,
});

export const idlService = IDL.Service({
  'findRashi' : IDL.Func([IDL.Text], [Rashi], ['query']),
  'getAllAstrologers' : IDL.Func([], [IDL.Vec(Astrologer)], ['query']),
  'getAllNumerology' : IDL.Func([], [IDL.Vec(Numerology)], ['query']),
  'getAllRashis' : IDL.Func([], [IDL.Vec(Rashi)], ['query']),
  'getAllVastuTips' : IDL.Func([], [IDL.Vec(VastuTip)], ['query']),
  'getAstrologersByExperience' : IDL.Func([], [IDL.Vec(Astrologer)], ['query']),
  'getAstrologersBySpecialization' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Astrologer)],
      ['query'],
    ),
  'getHoroscope' : IDL.Func([IDL.Text], [Horoscope], ['query']),
  'getKundaliRequest' : IDL.Func([IDL.Nat], [KundaliRequest], ['query']),
  'getNumerology' : IDL.Func([IDL.Nat], [Numerology], ['query']),
  'getVastuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(VastuTip)], ['query']),
  'submitKundaliRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateHoroscope' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Rashi = IDL.Record({
    'element' : IDL.Text,
    'description' : IDL.Text,
    'rulingPlanet' : IDL.Text,
    'englishName' : IDL.Text,
    'hindiName' : IDL.Text,
    'dateRange' : IDL.Text,
  });
  const Astrologer = IDL.Record({
    'name' : IDL.Text,
    'languages' : IDL.Text,
    'experience' : IDL.Nat,
    'specialization' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const Numerology = IDL.Record({
    'title' : IDL.Text,
    'strengths' : IDL.Text,
    'description' : IDL.Text,
    'number' : IDL.Nat,
    'challenges' : IDL.Text,
  });
  const VastuTip = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'benefit' : IDL.Text,
  });
  const Time = IDL.Int;
  const Horoscope = IDL.Record({
    'date' : Time,
    'message' : IDL.Text,
    'rashi' : IDL.Text,
  });
  const KundaliRequest = IDL.Record({
    'id' : IDL.Nat,
    'placeOfBirth' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timeOfBirth' : IDL.Text,
  });
  
  return IDL.Service({
    'findRashi' : IDL.Func([IDL.Text], [Rashi], ['query']),
    'getAllAstrologers' : IDL.Func([], [IDL.Vec(Astrologer)], ['query']),
    'getAllNumerology' : IDL.Func([], [IDL.Vec(Numerology)], ['query']),
    'getAllRashis' : IDL.Func([], [IDL.Vec(Rashi)], ['query']),
    'getAllVastuTips' : IDL.Func([], [IDL.Vec(VastuTip)], ['query']),
    'getAstrologersByExperience' : IDL.Func(
        [],
        [IDL.Vec(Astrologer)],
        ['query'],
      ),
    'getAstrologersBySpecialization' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Astrologer)],
        ['query'],
      ),
    'getHoroscope' : IDL.Func([IDL.Text], [Horoscope], ['query']),
    'getKundaliRequest' : IDL.Func([IDL.Nat], [KundaliRequest], ['query']),
    'getNumerology' : IDL.Func([IDL.Nat], [Numerology], ['query']),
    'getVastuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(VastuTip)], ['query']),
    'submitKundaliRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateHoroscope' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };