/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Astrologer {
  'name' : string,
  'languages' : string,
  'experience' : bigint,
  'specialization' : string,
  'rating' : number,
}
export interface Horoscope {
  'date' : Time,
  'message' : string,
  'rashi' : string,
}
export interface KundaliRequest {
  'id' : bigint,
  'placeOfBirth' : string,
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'timeOfBirth' : string,
}
export interface Numerology {
  'title' : string,
  'strengths' : string,
  'description' : string,
  'number' : bigint,
  'challenges' : string,
}
export interface Rashi {
  'element' : string,
  'description' : string,
  'rulingPlanet' : string,
  'englishName' : string,
  'hindiName' : string,
  'dateRange' : string,
}
export type Time = bigint;
export interface VastuTip {
  'title' : string,
  'description' : string,
  'category' : string,
  'benefit' : string,
}
export interface _SERVICE {
  'findRashi' : ActorMethod<[string], Rashi>,
  'getAllAstrologers' : ActorMethod<[], Array<Astrologer>>,
  'getAllNumerology' : ActorMethod<[], Array<Numerology>>,
  'getAllRashis' : ActorMethod<[], Array<Rashi>>,
  'getAllVastuTips' : ActorMethod<[], Array<VastuTip>>,
  'getAstrologersByExperience' : ActorMethod<[], Array<Astrologer>>,
  'getAstrologersBySpecialization' : ActorMethod<[string], Array<Astrologer>>,
  'getHoroscope' : ActorMethod<[string], Horoscope>,
  'getKundaliRequest' : ActorMethod<[bigint], KundaliRequest>,
  'getNumerology' : ActorMethod<[bigint], Numerology>,
  'getVastuByCategory' : ActorMethod<[string], Array<VastuTip>>,
  'submitKundaliRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateHoroscope' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];