/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VastuTip {
    title: string;
    description: string;
    category: string;
    benefit: string;
}
export type Time = bigint;
export interface KundaliRequest {
    id: bigint;
    placeOfBirth: string;
    dateOfBirth: string;
    name: string;
    email: string;
    timeOfBirth: string;
}
export interface Horoscope {
    date: Time;
    message: string;
    rashi: string;
}
export interface Astrologer {
    name: string;
    languages: string;
    experience: bigint;
    specialization: string;
    rating: number;
}
export interface Rashi {
    element: string;
    description: string;
    rulingPlanet: string;
    englishName: string;
    hindiName: string;
    dateRange: string;
}
export interface Numerology {
    title: string;
    strengths: string;
    description: string;
    number: bigint;
    challenges: string;
}
export interface backendInterface {
    findRashi(name: string): Promise<Rashi>;
    getAllAstrologers(): Promise<Array<Astrologer>>;
    getAllNumerology(): Promise<Array<Numerology>>;
    getAllRashis(): Promise<Array<Rashi>>;
    getAllVastuTips(): Promise<Array<VastuTip>>;
    getAstrologersByExperience(): Promise<Array<Astrologer>>;
    getAstrologersBySpecialization(specialization: string): Promise<Array<Astrologer>>;
    getHoroscope(rashi: string): Promise<Horoscope>;
    getKundaliRequest(id: bigint): Promise<KundaliRequest>;
    getNumerology(number: bigint): Promise<Numerology>;
    getVastuByCategory(category: string): Promise<Array<VastuTip>>;
    submitKundaliRequest(name: string, dateOfBirth: string, timeOfBirth: string, placeOfBirth: string, email: string): Promise<bigint>;
    updateHoroscope(rashi: string, message: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async findRashi(arg0: string): Promise<Rashi> {
        if (this.processError) {
            try {
                const result = await this.actor.findRashi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findRashi(arg0);
            return result;
        }
    }
    async getAllAstrologers(): Promise<Array<Astrologer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAstrologers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAstrologers();
            return result;
        }
    }
    async getAllNumerology(): Promise<Array<Numerology>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNumerology();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNumerology();
            return result;
        }
    }
    async getAllRashis(): Promise<Array<Rashi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRashis();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRashis();
            return result;
        }
    }
    async getAllVastuTips(): Promise<Array<VastuTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVastuTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVastuTips();
            return result;
        }
    }
    async getAstrologersByExperience(): Promise<Array<Astrologer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAstrologersByExperience();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAstrologersByExperience();
            return result;
        }
    }
    async getAstrologersBySpecialization(arg0: string): Promise<Array<Astrologer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAstrologersBySpecialization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAstrologersBySpecialization(arg0);
            return result;
        }
    }
    async getHoroscope(arg0: string): Promise<Horoscope> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoroscope(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoroscope(arg0);
            return result;
        }
    }
    async getKundaliRequest(arg0: bigint): Promise<KundaliRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getKundaliRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKundaliRequest(arg0);
            return result;
        }
    }
    async getNumerology(arg0: bigint): Promise<Numerology> {
        if (this.processError) {
            try {
                const result = await this.actor.getNumerology(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNumerology(arg0);
            return result;
        }
    }
    async getVastuByCategory(arg0: string): Promise<Array<VastuTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVastuByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVastuByCategory(arg0);
            return result;
        }
    }
    async submitKundaliRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKundaliRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKundaliRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateHoroscope(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHoroscope(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHoroscope(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
